export enum SCREEN {
  START_APP_SCREEN = 'Start-screen',
  ONBOARDING_SCREEN = 'Onboarding_screen',
  LOGIN_SCREEN = 'Login-screen',
  SIGNUP_SCREEN = 'Signup-screen',
  HOME_SCREEN = 'Home-screen',
  CALL_SCREEN = 'Call-screen',
  CONTACT_SCREEN = 'Contact-screen',
  SETTINGS_SCREEN = 'Setting-screen',
  ACCOUNT_SCREEN = 'Account-screen',
  EDITS_ACCOUNT = 'EditAccount-screen',
  CHAT_SCREEN = 'Chat-screen',
  SENDING_CALL = 'SendingCall-screen',
  INCOMING_CALL_SCREEN = 'IncominCall-screen',
  RECIVED_CALL_SCREEN = 'RecivedCall-screen',
  SEARCH_SCREEN = 'Search-screen',
  USER_STATUS = 'User-status',
}
